name: EclipseMaster2000
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - rawpy=0.25.0
  - matplotlib=3.10.3
  - scikit-image=0.25.2
  - numpy=2.2.6
  - opencv=4.11.0
  - pytest=8.4.0