name: eclipsetools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - rawpy=0.25.0
  - matplotlib=3.10.3
  - numpy=2.2.6
  - opencv=4.11.0
  - pytest=8.4.0
  - pytest-xdist=3.7.0
  - joblib=1.5.1
  - click=8.1.7
  - tifffile=2025.6.11
  - tqdm=4.67.1
  - scipy=1.15.2
  - scikit-learn=1.7.0
  - black=25.1.0